{- |
Module      : Cardano.Testnet.Baker.Genesis
Description : Cardano genesis and node configuration rendering.
Copyright   : (c) Paolo Veronelli, 2026
License     : Apache-2.0

Builds deterministic genesis files and node configuration from a
validated testnet scenario.
-}
module Cardano.Testnet.Baker.Genesis
    ( genesisArtifactBytes
    , renderShelleyGenesis
    ) where

import Cardano.Testnet.Baker.Keys (faucetPaymentAddressHex)
import Cardano.Testnet.Baker.Metadata (canonicalJsonBytes)
import Cardano.Testnet.Baker.Scenario
    ( EraSchedule (..)
    , FaucetDeclaration (..)
    , Network (..)
    , Scenario (..)
    , ScenarioGenesis (..)
    )
import Data.Aeson (Value, object, (.=))
import Data.Aeson.Key qualified as Key
import Data.ByteString.Lazy qualified as LBS
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import System.FilePath ((</>))

-- | Genesis artifacts generated by this feature slice.
genesisArtifactBytes :: Scenario -> [(FilePath, LBS.ByteString)]
genesisArtifactBytes scenario =
    [ ("genesis" </> "byron-genesis.json", renderByronGenesis scenario)
    , ("genesis" </> "shelley-genesis.json", renderShelleyGenesis scenario)
    , ("genesis" </> "alonzo-genesis.json", renderAlonzoGenesis)
    , ("genesis" </> "conway-genesis.json", renderConwayGenesis)
    , ("genesis" </> "config.json", renderNodeConfig scenario)
    ]

-- | Render Byron genesis JSON with a deterministic start-time placeholder.
renderByronGenesis :: Scenario -> LBS.ByteString
renderByronGenesis scenario =
    canonicalJsonBytes $
        object
            [ "avvmDistr" .= object []
            , "blockVersionData"
                .= object
                    [ "heavyDelThd" .= ("300000000000" :: String)
                    , "maxBlockSize" .= ("2000000" :: String)
                    , "maxHeaderSize" .= ("2000" :: String)
                    , "maxProposalSize" .= ("700" :: String)
                    , "maxTxSize" .= ("4096" :: String)
                    , "mpcThd" .= ("20000000000000" :: String)
                    , "scriptVersion" .= (0 :: Int)
                    , "slotDuration" .= ("20000" :: String)
                    , "softforkRule"
                        .= object
                            [ "initThd" .= ("900000000000000" :: String)
                            , "minThd" .= ("600000000000000" :: String)
                            , "thdDecrement"
                                .= ("50000000000000" :: String)
                            ]
                    , "txFeePolicy"
                        .= object
                            [ "multiplier" .= ("43946000000" :: String)
                            , "summand" .= ("155381000000000" :: String)
                            ]
                    , "unlockStakeEpoch"
                        .= ("18446744073709551615" :: String)
                    , "updateImplicit" .= ("10000" :: String)
                    , "updateProposalThd"
                        .= ("100000000000000" :: String)
                    , "updateVoteThd" .= ("1000000000000" :: String)
                    ]
            , "bootStakeholders" .= object []
            , "ftsSeed" .= object []
            , "heavyDelegation" .= object []
            , "nonAvvmBalances" .= object []
            , "protocolConsts"
                .= object
                    [ "k" .= scenarioGenesisSecurityParam genesis
                    , "protocolMagic" .= networkMagic (scenarioNetwork scenario)
                    , "vssMaxTTL" .= (6 :: Int)
                    , "vssMinTTL" .= (2 :: Int)
                    ]
            , "startTime" .= (0 :: Int)
            , "vssCerts" .= object []
            ]
  where
    genesis = scenarioGenesis scenario

-- | Render Shelley genesis JSON without run-specific start time fields.
renderShelleyGenesis :: Scenario -> LBS.ByteString
renderShelleyGenesis scenario =
    canonicalJsonBytes $
        object
            [ "activeSlotsCoeff"
                .= scenarioGenesisActiveSlotsCoeff genesis
            , "epochLength" .= scenarioGenesisEpochLength genesis
            , "genDelegs" .= object []
            , "initialFunds" .= faucetInitialFunds scenario
            , "maxKESEvolutions" .= (62 :: Int)
            , "maxLovelaceSupply"
                .= scenarioGenesisMaxLovelaceSupply genesis
            , "networkId" .= networkId (scenarioNetwork scenario)
            , "networkMagic" .= networkMagic (scenarioNetwork scenario)
            , "protocolParams" .= protocolParams genesis
            , "securityParam" .= scenarioGenesisSecurityParam genesis
            , "slotLength" .= (1 :: Int)
            , "slotsPerKESPeriod"
                .= scenarioGenesisEpochLength genesis
            , "staking"
                .= object
                    [ "pools" .= object []
                    , "stake" .= object []
                    ]
            , "updateQuorum" .= (1 :: Int)
            ]
  where
    genesis = scenarioGenesis scenario

renderAlonzoGenesis :: LBS.ByteString
renderAlonzoGenesis =
    canonicalJsonBytes $
        object
            [ "collateralPercentage" .= (150 :: Int)
            , "costModels" .= object []
            , "executionPrices"
                .= object
                    [ "prMem"
                        .= object
                            [ "denominator" .= (10000 :: Int)
                            , "numerator" .= (577 :: Int)
                            ]
                    , "prSteps"
                        .= object
                            [ "denominator" .= (10000000 :: Int)
                            , "numerator" .= (721 :: Int)
                            ]
                    ]
            , "lovelacePerUTxOWord" .= (34482 :: Integer)
            , "maxBlockExUnits"
                .= object
                    [ "exUnitsMem" .= (50000000 :: Integer)
                    , "exUnitsSteps" .= (40000000000 :: Integer)
                    ]
            , "maxCollateralInputs" .= (3 :: Int)
            , "maxTxExUnits"
                .= object
                    [ "exUnitsMem" .= (10000000 :: Integer)
                    , "exUnitsSteps" .= (10000000000 :: Integer)
                    ]
            , "maxValueSize" .= (5000 :: Int)
            ]

renderConwayGenesis :: LBS.ByteString
renderConwayGenesis =
    canonicalJsonBytes $
        object
            [ "committee"
                .= object
                    [ "members" .= object []
                    , "threshold" .= (0 :: Double)
                    ]
            , "committeeMaxTermLength" .= (0 :: Int)
            , "committeeMinSize" .= (0 :: Int)
            , "constitution"
                .= object
                    [ "anchor"
                        .= object
                            [ "dataHash" .= zeroHash
                            , "url" .= ("" :: String)
                            ]
                    ]
            , "dRepActivity" .= (0 :: Int)
            , "dRepDeposit" .= (0 :: Integer)
            , "dRepVotingThresholds" .= votingThresholds
            , "govActionDeposit" .= (0 :: Integer)
            , "govActionLifetime" .= (0 :: Int)
            , "minFeeRefScriptCostPerByte" .= (0 :: Int)
            , "plutusV3CostModel" .= replicate 230 (0 :: Int)
            , "poolVotingThresholds" .= poolVotingThresholds
            ]

renderNodeConfig :: Scenario -> LBS.ByteString
renderNodeConfig scenario =
    canonicalJsonBytes $
        object
            [ "AlonzoGenesisFile" .= ("alonzo-genesis.json" :: String)
            , "ByronGenesisFile" .= ("byron-genesis.json" :: String)
            , "ConwayGenesisFile" .= ("conway-genesis.json" :: String)
            , "EnableP2P" .= True
            , "ExperimentalHardForksEnabled" .= True
            , "ExperimentalProtocolsEnabled" .= True
            , "LastKnownBlockVersion-Alt" .= (0 :: Int)
            , "LastKnownBlockVersion-Major" .= (6 :: Int)
            , "LastKnownBlockVersion-Minor" .= (0 :: Int)
            , "MaxKnownMajorProtocolVersion" .= (2 :: Int)
            , "Protocol" .= ("Cardano" :: String)
            , "RequiresNetworkMagic"
                .= requiresNetworkMagic (scenarioNetwork scenario)
            , "ShelleyGenesisFile" .= ("shelley-genesis.json" :: String)
            , "TestAllegraHardForkAtEpoch"
                .= eraScheduleShelley schedule
            , "TestAlonzoHardForkAtEpoch" .= eraScheduleAlonzo schedule
            , "TestBabbageHardForkAtEpoch" .= eraScheduleAlonzo schedule
            , "TestConwayHardForkAtEpoch" .= eraScheduleConway schedule
            , "TestEnableDevelopmentHardForkEras" .= True
            , "TestEnableDevelopmentNetworkProtocols" .= True
            , "TestMaryHardForkAtEpoch" .= eraScheduleShelley schedule
            , "TestShelleyHardForkAtEpoch" .= eraScheduleShelley schedule
            , "TraceOptions"
                .= object
                    [ ""
                        .= object
                            [ "backends" .= ["Stdout MachineFormat" :: String]
                            , "severity" .= ("Notice" :: String)
                            ]
                    ]
            , "TurnOnLogMetrics" .= True
            , "TurnOnLogging" .= True
            , "UseTraceDispatcher" .= True
            ]
  where
    schedule = scenarioEraSchedule scenario

faucetInitialFunds :: Scenario -> Value
faucetInitialFunds scenario =
    object
        [ Key.fromText
            (faucetPaymentAddressHex seed (scenarioNetwork scenario) faucet)
            .= faucetLovelace faucet
        | faucet <- scenarioFaucets scenario
        ]
  where
    seed = TextEncoding.encodeUtf8 (scenarioSeed scenario)

protocolParams :: ScenarioGenesis -> Value
protocolParams genesis =
    object
        [ "a0" .= (0.3 :: Double)
        , "decentralisationParam" .= (0 :: Int)
        , "eMax" .= (18 :: Int)
        , "extraEntropy"
            .= object
                [ "tag" .= ("NeutralNonce" :: String)
                ]
        , "keyDeposit" .= (2000000 :: Integer)
        , "maxBlockBodySize" .= (90112 :: Int)
        , "maxBlockHeaderSize" .= (1100 :: Int)
        , "maxTxSize" .= (16384 :: Int)
        , "minFeeA" .= (44 :: Int)
        , "minFeeB" .= (155381 :: Int)
        , "minPoolCost" .= (340000000 :: Integer)
        , "minUTxOValue" .= (1000000 :: Integer)
        , "nOpt" .= scenarioGenesisK genesis
        , "poolDeposit" .= (500000000 :: Integer)
        , "protocolVersion"
            .= object
                [ "major" .= (10 :: Int)
                , "minor" .= (0 :: Int)
                ]
        , "rho" .= (0.003 :: Double)
        , "tau" .= (0.2 :: Double)
        ]

requiresNetworkMagic :: Network -> String
requiresNetworkMagic network =
    case Text.toCaseFold (networkId network) of
        "mainnet" -> "RequiresNoMagic"
        _ -> "RequiresMagic"

votingThresholds :: Value
votingThresholds =
    object
        [ "committeeNoConfidence" .= (0 :: Double)
        , "committeeNormal" .= (0 :: Double)
        , "hardForkInitiation" .= (0 :: Double)
        , "motionNoConfidence" .= (0 :: Double)
        , "ppEconomicGroup" .= (0 :: Double)
        , "ppGovGroup" .= (0 :: Double)
        , "ppNetworkGroup" .= (0 :: Double)
        , "ppTechnicalGroup" .= (0 :: Double)
        , "treasuryWithdrawal" .= (0 :: Double)
        , "updateToConstitution" .= (0 :: Double)
        ]

poolVotingThresholds :: Value
poolVotingThresholds =
    object
        [ "committeeNoConfidence" .= (0 :: Double)
        , "committeeNormal" .= (0 :: Double)
        , "hardForkInitiation" .= (0 :: Double)
        , "motionNoConfidence" .= (0 :: Double)
        , "ppSecurityGroup" .= (0 :: Double)
        ]

zeroHash :: String
zeroHash =
    "0000000000000000000000000000000000000000000000000000000000000000"
