{- |
Module      : Cardano.Testnet.Baker.Genesis
Description : Cardano genesis and node configuration rendering.
Copyright   : (c) Paolo Veronelli, 2026
License     : Apache-2.0

Builds deterministic genesis files and node configuration from a
validated testnet scenario.
-}
module Cardano.Testnet.Baker.Genesis
    ( genesisArtifactBytes
    , renderShelleyGenesis
    ) where

import Cardano.Testnet.Baker.Keys (faucetPaymentAddressHex)
import Cardano.Testnet.Baker.Metadata (canonicalJsonBytes)
import Cardano.Testnet.Baker.Scenario
    ( FaucetDeclaration (..)
    , Network (..)
    , Scenario (..)
    , ScenarioGenesis (..)
    )
import Data.Aeson (Value, object, (.=))
import Data.Aeson.Key qualified as Key
import Data.ByteString.Lazy qualified as LBS
import Data.Text.Encoding qualified as TextEncoding
import System.FilePath ((</>))

-- | Genesis artifacts generated by this feature slice.
genesisArtifactBytes :: Scenario -> [(FilePath, LBS.ByteString)]
genesisArtifactBytes scenario =
    [ ("genesis" </> "shelley-genesis.json", renderShelleyGenesis scenario)
    ]

-- | Render Shelley genesis JSON without run-specific start time fields.
renderShelleyGenesis :: Scenario -> LBS.ByteString
renderShelleyGenesis scenario =
    canonicalJsonBytes $
        object
            [ "activeSlotsCoeff"
                .= scenarioGenesisActiveSlotsCoeff genesis
            , "epochLength" .= scenarioGenesisEpochLength genesis
            , "genDelegs" .= object []
            , "initialFunds" .= faucetInitialFunds scenario
            , "maxKESEvolutions" .= (62 :: Int)
            , "maxLovelaceSupply"
                .= scenarioGenesisMaxLovelaceSupply genesis
            , "networkId" .= networkId (scenarioNetwork scenario)
            , "networkMagic" .= networkMagic (scenarioNetwork scenario)
            , "protocolParams" .= protocolParams genesis
            , "securityParam" .= scenarioGenesisSecurityParam genesis
            , "slotLength" .= (1 :: Int)
            , "slotsPerKESPeriod"
                .= scenarioGenesisEpochLength genesis
            , "staking"
                .= object
                    [ "pools" .= object []
                    , "stake" .= object []
                    ]
            , "updateQuorum" .= (1 :: Int)
            ]
  where
    genesis = scenarioGenesis scenario

faucetInitialFunds :: Scenario -> Value
faucetInitialFunds scenario =
    object
        [ Key.fromText
            (faucetPaymentAddressHex seed (scenarioNetwork scenario) faucet)
            .= faucetLovelace faucet
        | faucet <- scenarioFaucets scenario
        ]
  where
    seed = TextEncoding.encodeUtf8 (scenarioSeed scenario)

protocolParams :: ScenarioGenesis -> Value
protocolParams genesis =
    object
        [ "a0" .= (0.3 :: Double)
        , "decentralisationParam" .= (0 :: Int)
        , "eMax" .= (18 :: Int)
        , "extraEntropy"
            .= object
                [ "tag" .= ("NeutralNonce" :: String)
                ]
        , "keyDeposit" .= (2000000 :: Integer)
        , "maxBlockBodySize" .= (90112 :: Int)
        , "maxBlockHeaderSize" .= (1100 :: Int)
        , "maxTxSize" .= (16384 :: Int)
        , "minFeeA" .= (44 :: Int)
        , "minFeeB" .= (155381 :: Int)
        , "minPoolCost" .= (340000000 :: Integer)
        , "minUTxOValue" .= (1000000 :: Integer)
        , "nOpt" .= scenarioGenesisK genesis
        , "poolDeposit" .= (500000000 :: Integer)
        , "protocolVersion"
            .= object
                [ "major" .= (10 :: Int)
                , "minor" .= (0 :: Int)
                ]
        , "rho" .= (0.003 :: Double)
        , "tau" .= (0.2 :: Double)
        ]
