{- |
Module      : Cardano.Testnet.Baker.Genesis
Description : Cardano genesis and node configuration rendering.
Copyright   : (c) Paolo Veronelli, 2026
License     : Apache-2.0

Builds deterministic genesis files and node configuration from a
validated testnet scenario.
-}
module Cardano.Testnet.Baker.Genesis
    ( genesisArtifactBytes
    , renderShelleyGenesis
    ) where

import Cardano.Testnet.Baker.Keys (faucetPaymentAddressHex)
import Cardano.Testnet.Baker.Metadata (canonicalJsonBytes)
import Cardano.Testnet.Baker.Scenario
    ( EraSchedule (..)
    , FaucetDeclaration (..)
    , Network (..)
    , Scenario (..)
    , ScenarioGenesis (..)
    )
import Data.Aeson (Value, object, (.=))
import Data.Aeson.Key qualified as Key
import Data.ByteString.Lazy qualified as LBS
import Data.Text qualified as Text
import Data.Text.Encoding qualified as TextEncoding
import System.FilePath ((</>))

-- | Genesis artifacts generated by this feature slice.
genesisArtifactBytes :: Scenario -> [(FilePath, LBS.ByteString)]
genesisArtifactBytes scenario =
    [ ("genesis" </> "byron-genesis.json", renderByronGenesis scenario)
    , ("genesis" </> "shelley-genesis.json", renderShelleyGenesis scenario)
    , ("genesis" </> "alonzo-genesis.json", renderAlonzoGenesis)
    , ("genesis" </> "conway-genesis.json", renderConwayGenesis)
    , ("genesis" </> "config.json", renderNodeConfig scenario)
    ]

-- | Render Byron genesis JSON with a deterministic start-time placeholder.
renderByronGenesis :: Scenario -> LBS.ByteString
renderByronGenesis scenario =
    canonicalJsonBytes $
        object
            [ "avvmDistr" .= object []
            , "blockVersionData"
                .= object
                    [ "heavyDelThd" .= ("300000000000" :: String)
                    , "maxBlockSize" .= ("2000000" :: String)
                    , "maxHeaderSize" .= ("2000" :: String)
                    , "maxProposalSize" .= ("700" :: String)
                    , "maxTxSize" .= ("4096" :: String)
                    , "mpcThd" .= ("20000000000000" :: String)
                    , "scriptVersion" .= (0 :: Int)
                    , "slotDuration" .= ("20000" :: String)
                    , "softforkRule"
                        .= object
                            [ "initThd" .= ("900000000000000" :: String)
                            , "minThd" .= ("600000000000000" :: String)
                            , "thdDecrement"
                                .= ("50000000000000" :: String)
                            ]
                    , "txFeePolicy"
                        .= object
                            [ "multiplier" .= ("43946000000" :: String)
                            , "summand" .= ("155381000000000" :: String)
                            ]
                    , "unlockStakeEpoch"
                        .= ("18446744073709551615" :: String)
                    , "updateImplicit" .= ("10000" :: String)
                    , "updateProposalThd"
                        .= ("100000000000000" :: String)
                    , "updateVoteThd" .= ("1000000000000" :: String)
                    ]
            , "bootStakeholders" .= object []
            , "ftsSeed" .= object []
            , "heavyDelegation" .= object []
            , "nonAvvmBalances" .= object []
            , "protocolConsts"
                .= object
                    [ "k" .= scenarioGenesisSecurityParam genesis
                    , "protocolMagic" .= networkMagic (scenarioNetwork scenario)
                    , "vssMaxTTL" .= (6 :: Int)
                    , "vssMinTTL" .= (2 :: Int)
                    ]
            , "startTime" .= (0 :: Int)
            , "vssCerts" .= object []
            ]
  where
    genesis = scenarioGenesis scenario

-- | Render Shelley genesis JSON without run-specific start time fields.
renderShelleyGenesis :: Scenario -> LBS.ByteString
renderShelleyGenesis scenario =
    canonicalJsonBytes $
        object
            [ "activeSlotsCoeff"
                .= scenarioGenesisActiveSlotsCoeff genesis
            , "epochLength" .= scenarioGenesisEpochLength genesis
            , "genDelegs" .= object []
            , "initialFunds" .= faucetInitialFunds scenario
            , "maxKESEvolutions" .= (62 :: Int)
            , "maxLovelaceSupply"
                .= scenarioGenesisMaxLovelaceSupply genesis
            , "networkId" .= networkId (scenarioNetwork scenario)
            , "networkMagic" .= networkMagic (scenarioNetwork scenario)
            , "protocolParams" .= protocolParams genesis
            , "securityParam" .= scenarioGenesisSecurityParam genesis
            , "slotLength" .= (1 :: Int)
            , "slotsPerKESPeriod"
                .= scenarioGenesisEpochLength genesis
            , "staking"
                .= object
                    [ "pools" .= object []
                    , "stake" .= object []
                    ]
            , "updateQuorum" .= (1 :: Int)
            ]
  where
    genesis = scenarioGenesis scenario

renderAlonzoGenesis :: LBS.ByteString
renderAlonzoGenesis =
    canonicalJsonBytes $
        object
            [ "collateralPercentage" .= (150 :: Int)
            , "costModels"
                .= object
                    [ "PlutusV1" .= plutusV1CostModel
                    ]
            , "executionPrices"
                .= object
                    [ "prMem"
                        .= object
                            [ "denominator" .= (10000 :: Int)
                            , "numerator" .= (577 :: Int)
                            ]
                    , "prSteps"
                        .= object
                            [ "denominator" .= (10000000 :: Int)
                            , "numerator" .= (721 :: Int)
                            ]
                    ]
            , "lovelacePerUTxOWord" .= (34482 :: Integer)
            , "maxBlockExUnits"
                .= object
                    [ "exUnitsMem" .= (50000000 :: Integer)
                    , "exUnitsSteps" .= (40000000000 :: Integer)
                    ]
            , "maxCollateralInputs" .= (3 :: Int)
            , "maxTxExUnits"
                .= object
                    [ "exUnitsMem" .= (10000000 :: Integer)
                    , "exUnitsSteps" .= (10000000000 :: Integer)
                    ]
            , "maxValueSize" .= (5000 :: Int)
            ]

plutusV1CostModel :: Value
plutusV1CostModel =
    object
        [ "addInteger-cpu-arguments-intercept" .= (197209 :: Int)
        , "addInteger-cpu-arguments-slope" .= (0 :: Int)
        , "addInteger-memory-arguments-intercept" .= (1 :: Int)
        , "addInteger-memory-arguments-slope" .= (1 :: Int)
        , "appendByteString-cpu-arguments-intercept" .= (396231 :: Int)
        , "appendByteString-cpu-arguments-slope" .= (621 :: Int)
        , "appendByteString-memory-arguments-intercept" .= (0 :: Int)
        , "appendByteString-memory-arguments-slope" .= (1 :: Int)
        , "appendString-cpu-arguments-intercept" .= (150000 :: Int)
        , "appendString-cpu-arguments-slope" .= (1000 :: Int)
        , "appendString-memory-arguments-intercept" .= (0 :: Int)
        , "appendString-memory-arguments-slope" .= (1 :: Int)
        , "bData-cpu-arguments" .= (150000 :: Int)
        , "bData-memory-arguments" .= (32 :: Int)
        , "blake2b-cpu-arguments-intercept" .= (2477736 :: Int)
        , "blake2b-cpu-arguments-slope" .= (29175 :: Int)
        , "blake2b-memory-arguments" .= (4 :: Int)
        , "cekApplyCost-exBudgetCPU" .= (29773 :: Int)
        , "cekApplyCost-exBudgetMemory" .= (100 :: Int)
        , "cekBuiltinCost-exBudgetCPU" .= (29773 :: Int)
        , "cekBuiltinCost-exBudgetMemory" .= (100 :: Int)
        , "cekConstCost-exBudgetCPU" .= (29773 :: Int)
        , "cekConstCost-exBudgetMemory" .= (100 :: Int)
        , "cekDelayCost-exBudgetCPU" .= (29773 :: Int)
        , "cekDelayCost-exBudgetMemory" .= (100 :: Int)
        , "cekForceCost-exBudgetCPU" .= (29773 :: Int)
        , "cekForceCost-exBudgetMemory" .= (100 :: Int)
        , "cekLamCost-exBudgetCPU" .= (29773 :: Int)
        , "cekLamCost-exBudgetMemory" .= (100 :: Int)
        , "cekStartupCost-exBudgetCPU" .= (100 :: Int)
        , "cekStartupCost-exBudgetMemory" .= (100 :: Int)
        , "cekVarCost-exBudgetCPU" .= (29773 :: Int)
        , "cekVarCost-exBudgetMemory" .= (100 :: Int)
        , "chooseData-cpu-arguments" .= (150000 :: Int)
        , "chooseData-memory-arguments" .= (32 :: Int)
        , "chooseList-cpu-arguments" .= (150000 :: Int)
        , "chooseList-memory-arguments" .= (32 :: Int)
        , "chooseUnit-cpu-arguments" .= (150000 :: Int)
        , "chooseUnit-memory-arguments" .= (32 :: Int)
        , "consByteString-cpu-arguments-intercept" .= (150000 :: Int)
        , "consByteString-cpu-arguments-slope" .= (1000 :: Int)
        , "consByteString-memory-arguments-intercept" .= (0 :: Int)
        , "consByteString-memory-arguments-slope" .= (1 :: Int)
        , "constrData-cpu-arguments" .= (150000 :: Int)
        , "constrData-memory-arguments" .= (32 :: Int)
        , "decodeUtf8-cpu-arguments-intercept" .= (150000 :: Int)
        , "decodeUtf8-cpu-arguments-slope" .= (1000 :: Int)
        , "decodeUtf8-memory-arguments-intercept" .= (0 :: Int)
        , "decodeUtf8-memory-arguments-slope" .= (8 :: Int)
        , "divideInteger-cpu-arguments-constant" .= (148000 :: Int)
        , "divideInteger-cpu-arguments-model-arguments-intercept"
            .= (425507 :: Int)
        , "divideInteger-cpu-arguments-model-arguments-slope" .= (118 :: Int)
        , "divideInteger-memory-arguments-intercept" .= (0 :: Int)
        , "divideInteger-memory-arguments-minimum" .= (1 :: Int)
        , "divideInteger-memory-arguments-slope" .= (1 :: Int)
        , "encodeUtf8-cpu-arguments-intercept" .= (150000 :: Int)
        , "encodeUtf8-cpu-arguments-slope" .= (1000 :: Int)
        , "encodeUtf8-memory-arguments-intercept" .= (0 :: Int)
        , "encodeUtf8-memory-arguments-slope" .= (8 :: Int)
        , "equalsByteString-cpu-arguments-constant" .= (150000 :: Int)
        , "equalsByteString-cpu-arguments-intercept" .= (112536 :: Int)
        , "equalsByteString-cpu-arguments-slope" .= (247 :: Int)
        , "equalsByteString-memory-arguments" .= (1 :: Int)
        , "equalsData-cpu-arguments-intercept" .= (150000 :: Int)
        , "equalsData-cpu-arguments-slope" .= (10000 :: Int)
        , "equalsData-memory-arguments" .= (1 :: Int)
        , "equalsInteger-cpu-arguments-intercept" .= (136542 :: Int)
        , "equalsInteger-cpu-arguments-slope" .= (1326 :: Int)
        , "equalsInteger-memory-arguments" .= (1 :: Int)
        , "equalsString-cpu-arguments-constant" .= (1000 :: Int)
        , "equalsString-cpu-arguments-intercept" .= (150000 :: Int)
        , "equalsString-cpu-arguments-slope" .= (1000 :: Int)
        , "equalsString-memory-arguments" .= (1 :: Int)
        , "fstPair-cpu-arguments" .= (150000 :: Int)
        , "fstPair-memory-arguments" .= (32 :: Int)
        , "headList-cpu-arguments" .= (150000 :: Int)
        , "headList-memory-arguments" .= (32 :: Int)
        , "iData-cpu-arguments" .= (150000 :: Int)
        , "iData-memory-arguments" .= (32 :: Int)
        , "ifThenElse-cpu-arguments" .= (1 :: Int)
        , "ifThenElse-memory-arguments" .= (1 :: Int)
        , "indexByteString-cpu-arguments" .= (150000 :: Int)
        , "indexByteString-memory-arguments" .= (1 :: Int)
        , "lengthOfByteString-cpu-arguments" .= (150000 :: Int)
        , "lengthOfByteString-memory-arguments" .= (4 :: Int)
        , "lessThanByteString-cpu-arguments-intercept" .= (103599 :: Int)
        , "lessThanByteString-cpu-arguments-slope" .= (248 :: Int)
        , "lessThanByteString-memory-arguments" .= (1 :: Int)
        , "lessThanEqualsByteString-cpu-arguments-intercept" .= (103599 :: Int)
        , "lessThanEqualsByteString-cpu-arguments-slope" .= (248 :: Int)
        , "lessThanEqualsByteString-memory-arguments" .= (1 :: Int)
        , "lessThanEqualsInteger-cpu-arguments-intercept" .= (145276 :: Int)
        , "lessThanEqualsInteger-cpu-arguments-slope" .= (1366 :: Int)
        , "lessThanEqualsInteger-memory-arguments" .= (1 :: Int)
        , "lessThanInteger-cpu-arguments-intercept" .= (179690 :: Int)
        , "lessThanInteger-cpu-arguments-slope" .= (497 :: Int)
        , "lessThanInteger-memory-arguments" .= (1 :: Int)
        , "listData-cpu-arguments" .= (150000 :: Int)
        , "listData-memory-arguments" .= (32 :: Int)
        , "mapData-cpu-arguments" .= (150000 :: Int)
        , "mapData-memory-arguments" .= (32 :: Int)
        , "mkCons-cpu-arguments" .= (150000 :: Int)
        , "mkCons-memory-arguments" .= (32 :: Int)
        , "mkNilData-cpu-arguments" .= (150000 :: Int)
        , "mkNilData-memory-arguments" .= (32 :: Int)
        , "mkNilPairData-cpu-arguments" .= (150000 :: Int)
        , "mkNilPairData-memory-arguments" .= (32 :: Int)
        , "mkPairData-cpu-arguments" .= (150000 :: Int)
        , "mkPairData-memory-arguments" .= (32 :: Int)
        , "modInteger-cpu-arguments-constant" .= (148000 :: Int)
        , "modInteger-cpu-arguments-model-arguments-intercept"
            .= (425507 :: Int)
        , "modInteger-cpu-arguments-model-arguments-slope" .= (118 :: Int)
        , "modInteger-memory-arguments-intercept" .= (0 :: Int)
        , "modInteger-memory-arguments-minimum" .= (1 :: Int)
        , "modInteger-memory-arguments-slope" .= (1 :: Int)
        , "multiplyInteger-cpu-arguments-intercept" .= (61516 :: Int)
        , "multiplyInteger-cpu-arguments-slope" .= (11218 :: Int)
        , "multiplyInteger-memory-arguments-intercept" .= (0 :: Int)
        , "multiplyInteger-memory-arguments-slope" .= (1 :: Int)
        , "nullList-cpu-arguments" .= (150000 :: Int)
        , "nullList-memory-arguments" .= (32 :: Int)
        , "quotientInteger-cpu-arguments-constant" .= (148000 :: Int)
        , "quotientInteger-cpu-arguments-model-arguments-intercept"
            .= (425507 :: Int)
        , "quotientInteger-cpu-arguments-model-arguments-slope" .= (118 :: Int)
        , "quotientInteger-memory-arguments-intercept" .= (0 :: Int)
        , "quotientInteger-memory-arguments-minimum" .= (1 :: Int)
        , "quotientInteger-memory-arguments-slope" .= (1 :: Int)
        , "remainderInteger-cpu-arguments-constant" .= (148000 :: Int)
        , "remainderInteger-cpu-arguments-model-arguments-intercept"
            .= (425507 :: Int)
        , "remainderInteger-cpu-arguments-model-arguments-slope" .= (118 :: Int)
        , "remainderInteger-memory-arguments-intercept" .= (0 :: Int)
        , "remainderInteger-memory-arguments-minimum" .= (1 :: Int)
        , "remainderInteger-memory-arguments-slope" .= (1 :: Int)
        , "sha2_256-cpu-arguments-intercept" .= (2477736 :: Int)
        , "sha2_256-cpu-arguments-slope" .= (29175 :: Int)
        , "sha2_256-memory-arguments" .= (4 :: Int)
        , "sha3_256-cpu-arguments-intercept" .= (0 :: Int)
        , "sha3_256-cpu-arguments-slope" .= (82363 :: Int)
        , "sha3_256-memory-arguments" .= (4 :: Int)
        , "sliceByteString-cpu-arguments-intercept" .= (150000 :: Int)
        , "sliceByteString-cpu-arguments-slope" .= (5000 :: Int)
        , "sliceByteString-memory-arguments-intercept" .= (0 :: Int)
        , "sliceByteString-memory-arguments-slope" .= (1 :: Int)
        , "sndPair-cpu-arguments" .= (150000 :: Int)
        , "sndPair-memory-arguments" .= (32 :: Int)
        , "subtractInteger-cpu-arguments-intercept" .= (197209 :: Int)
        , "subtractInteger-cpu-arguments-slope" .= (0 :: Int)
        , "subtractInteger-memory-arguments-intercept" .= (1 :: Int)
        , "subtractInteger-memory-arguments-slope" .= (1 :: Int)
        , "tailList-cpu-arguments" .= (150000 :: Int)
        , "tailList-memory-arguments" .= (32 :: Int)
        , "trace-cpu-arguments" .= (150000 :: Int)
        , "trace-memory-arguments" .= (32 :: Int)
        , "unBData-cpu-arguments" .= (150000 :: Int)
        , "unBData-memory-arguments" .= (32 :: Int)
        , "unConstrData-cpu-arguments" .= (150000 :: Int)
        , "unConstrData-memory-arguments" .= (32 :: Int)
        , "unIData-cpu-arguments" .= (150000 :: Int)
        , "unIData-memory-arguments" .= (32 :: Int)
        , "unListData-cpu-arguments" .= (150000 :: Int)
        , "unListData-memory-arguments" .= (32 :: Int)
        , "unMapData-cpu-arguments" .= (150000 :: Int)
        , "unMapData-memory-arguments" .= (32 :: Int)
        , "verifySignature-cpu-arguments-intercept" .= (3345831 :: Int)
        , "verifySignature-cpu-arguments-slope" .= (1 :: Int)
        , "verifySignature-memory-arguments" .= (1 :: Int)
        ]

renderConwayGenesis :: LBS.ByteString
renderConwayGenesis =
    canonicalJsonBytes $
        object
            [ "committee"
                .= object
                    [ "members" .= object []
                    , "threshold" .= (0 :: Double)
                    ]
            , "committeeMaxTermLength" .= (0 :: Int)
            , "committeeMinSize" .= (0 :: Int)
            , "constitution"
                .= object
                    [ "anchor"
                        .= object
                            [ "dataHash" .= zeroHash
                            , "url" .= ("" :: String)
                            ]
                    ]
            , "dRepActivity" .= (0 :: Int)
            , "dRepDeposit" .= (0 :: Integer)
            , "dRepVotingThresholds" .= votingThresholds
            , "govActionDeposit" .= (0 :: Integer)
            , "govActionLifetime" .= (0 :: Int)
            , "minFeeRefScriptCostPerByte" .= (0 :: Int)
            , "plutusV3CostModel" .= replicate 251 (0 :: Int)
            , "poolVotingThresholds" .= poolVotingThresholds
            ]

renderNodeConfig :: Scenario -> LBS.ByteString
renderNodeConfig scenario =
    canonicalJsonBytes $
        object
            [ "AlonzoGenesisFile" .= ("alonzo-genesis.json" :: String)
            , "ByronGenesisFile" .= ("byron-genesis.json" :: String)
            , "ConsensusMode" .= ("GenesisMode" :: String)
            , "ConwayGenesisFile" .= ("conway-genesis.json" :: String)
            , "EnableP2P" .= True
            , "ExperimentalHardForksEnabled" .= False
            , "ExperimentalProtocolsEnabled" .= False
            , "LastKnownBlockVersion-Alt" .= (0 :: Int)
            , "LastKnownBlockVersion-Major" .= (6 :: Int)
            , "LastKnownBlockVersion-Minor" .= (0 :: Int)
            , "Protocol" .= ("Cardano" :: String)
            , "RequiresNetworkMagic"
                .= requiresNetworkMagic (scenarioNetwork scenario)
            , "ShelleyGenesisFile" .= ("shelley-genesis.json" :: String)
            , "TestAllegraHardForkAtEpoch"
                .= eraScheduleShelley schedule
            , "TestAlonzoHardForkAtEpoch" .= eraScheduleAlonzo schedule
            , "TestBabbageHardForkAtEpoch" .= eraScheduleAlonzo schedule
            , "TestConwayHardForkAtEpoch" .= eraScheduleConway schedule
            , "TestMaryHardForkAtEpoch" .= eraScheduleShelley schedule
            , "TestShelleyHardForkAtEpoch" .= eraScheduleShelley schedule
            , "TraceOptions"
                .= object
                    [ ""
                        .= object
                            [ "backends" .= ["Stdout MachineFormat" :: String]
                            , "severity" .= ("Notice" :: String)
                            ]
                    ]
            , "TurnOnLogMetrics" .= True
            , "TurnOnLogging" .= True
            , "UseTraceDispatcher" .= True
            ]
  where
    schedule = scenarioEraSchedule scenario

faucetInitialFunds :: Scenario -> Value
faucetInitialFunds scenario =
    object
        [ Key.fromText
            (faucetPaymentAddressHex seed (scenarioNetwork scenario) faucet)
            .= faucetLovelace faucet
        | faucet <- scenarioFaucets scenario
        ]
  where
    seed = TextEncoding.encodeUtf8 (scenarioSeed scenario)

protocolParams :: ScenarioGenesis -> Value
protocolParams genesis =
    object
        [ "a0" .= (0.3 :: Double)
        , "decentralisationParam" .= (0 :: Int)
        , "eMax" .= (18 :: Int)
        , "extraEntropy"
            .= object
                [ "tag" .= ("NeutralNonce" :: String)
                ]
        , "keyDeposit" .= (2000000 :: Integer)
        , "maxBlockBodySize" .= (90112 :: Int)
        , "maxBlockHeaderSize" .= (1100 :: Int)
        , "maxTxSize" .= (16384 :: Int)
        , "minFeeA" .= (44 :: Int)
        , "minFeeB" .= (155381 :: Int)
        , "minPoolCost" .= (340000000 :: Integer)
        , "minUTxOValue" .= (1000000 :: Integer)
        , "nOpt" .= scenarioGenesisK genesis
        , "poolDeposit" .= (500000000 :: Integer)
        , "protocolVersion"
            .= object
                [ "major" .= (10 :: Int)
                , "minor" .= (0 :: Int)
                ]
        , "rho" .= (0.003 :: Double)
        , "tau" .= (0.2 :: Double)
        ]

requiresNetworkMagic :: Network -> String
requiresNetworkMagic network =
    case Text.toCaseFold (networkId network) of
        "mainnet" -> "RequiresNoMagic"
        _ -> "RequiresMagic"

votingThresholds :: Value
votingThresholds =
    object
        [ "committeeNoConfidence" .= (0 :: Double)
        , "committeeNormal" .= (0 :: Double)
        , "hardForkInitiation" .= (0 :: Double)
        , "motionNoConfidence" .= (0 :: Double)
        , "ppEconomicGroup" .= (0 :: Double)
        , "ppGovGroup" .= (0 :: Double)
        , "ppNetworkGroup" .= (0 :: Double)
        , "ppTechnicalGroup" .= (0 :: Double)
        , "treasuryWithdrawal" .= (0 :: Double)
        , "updateToConstitution" .= (0 :: Double)
        ]

poolVotingThresholds :: Value
poolVotingThresholds =
    object
        [ "committeeNoConfidence" .= (0 :: Double)
        , "committeeNormal" .= (0 :: Double)
        , "hardForkInitiation" .= (0 :: Double)
        , "motionNoConfidence" .= (0 :: Double)
        , "ppSecurityGroup" .= (0 :: Double)
        ]

zeroHash :: String
zeroHash =
    "0000000000000000000000000000000000000000000000000000000000000000"
