{- |
Module      : Cardano.Testnet.Baker.Dressing.Topology
Description : Per-pool topology.json generators.
Copyright   : (c) Paolo Veronelli, 2026
License     : Apache-2.0

A 'Topology' value captures the inter-pool connectivity rule.
'renderTopology' turns a topology + a layout's host-name function + a
'PoolIx' + a 'NumPools' into the @topology.json@ structure
@cardano-node@ expects.  The dressing layer renders one topology per
pool, so per-pool variation is in the 'PoolIx' argument rather than
inside the 'Topology' value.

The sum type is intentionally closed: each new connectivity rule
lands as a constructor, not as an open-class typeclass.  This keeps
the rendering exhaustive and the supported set small.
-}
module Cardano.Testnet.Baker.Dressing.Topology
    ( Topology (..)
    , renderTopology
    , antithesisTopology
    ) where

import Cardano.Testnet.Baker.Dressing.Layout
    ( NumPools (..)
    , PoolIx (..)
    )
import Data.Aeson (Value, object, (.=))
import Data.Text (Text)

-- | Inter-pool connectivity rule.
data Topology
    = {- | Bidirectional ring: pool @n@ connects to pool @n-1@ and
      pool @n+1@ (wrapping at the boundaries).  Matches the
      topology generated by the configurator's @config_topology_json@.
      -}
      Ring
      { ringValency :: !Int
      , ringAdvertise :: !Bool
      , ringTrustable :: !Bool
      }
    deriving (Eq, Show)

{- | Default ring used by the @antithesis-configurator@ profile:
valency 2, advertised, trustable.
-}
antithesisTopology :: Topology
antithesisTopology =
    Ring
        { ringValency = 2
        , ringAdvertise = True
        , ringTrustable = True
        }

{- | Render the per-pool @topology.json@ value.

For the ring topology the access points are ordered
@[previous, next]@ (with wrap-around), matching the bash adapter's
emission order.  Hosts are looked up via the supplied function so
the same renderer works for any 'Layout'.
-}
renderTopology
    :: Topology
    -> (PoolIx -> Text)
    -> PoolIx
    -> NumPools
    -> Value
renderTopology Ring{..} hostOf (PoolIx me) (NumPools n) =
    object
        [ "localRoots"
            .= [ object
                    [ "accessPoints" .= [host prevIx, host nextIx]
                    , "advertise" .= ringAdvertise
                    , "trustable" .= ringTrustable
                    , "valency" .= ringValency
                    ]
               ]
        , "publicRoots" .= ([] :: [Value])
        , "useLedgerAfterSlot" .= (0 :: Int)
        ]
  where
    prevIx =
        PoolIx $
            if me - 1 < 1 then n else me - 1
    nextIx =
        PoolIx $
            if me + 1 > n then 1 else me + 1
    host ix = object ["address" .= hostOf ix, "port" .= (3001 :: Int)]
